#!/bin/bash

echo "📦 Applying blocks table migration to Supabase..."
echo ""
echo "⚠️  Please do ONE of the following:"
echo ""
echo "Option 1 - Supabase Dashboard (RECOMMENDED):"
echo "  1. Go to your Supabase project dashboard"
echo "  2. Click on 'SQL Editor' in the sidebar"
echo "  3. Create a new query"
echo "  4. Copy and paste the contents of:"
echo "     supabase/migrations/20251116_create_blocks_table.sql"
echo "  5. Click 'Run'"
echo ""
echo "Option 2 - Supabase CLI:"
echo "  supabase db push"
echo ""
echo "The migration will create:"
echo "  ✓ blocks table"
echo "  ✓ RLS policies"
echo "  ✓ block_user() function"
echo "  ✓ unblock_user() function"
echo "  ✓ has_blocked() function"
echo ""
